name: croupier
description: A custom SocketCluster client implementation for Dart and Flutter.
version: 1.0.1+1
repository: https://github.com/SamJakob/croupier

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  meta: ^1.7.0

dev_dependencies:
  lints: ^1.0.1
  test: ^1.20.2
