name: croupier
description: A custom SocketCluster client implementation for Dart and Flutter.
version: 1.0.0+1
repository: https://github.com/SamJakob/croupier

environment:
  sdk: '>=2.10.0 <3.0.0'

dependencies:
  meta: ^1.2.4

dev_dependencies:
  pedantic: ^1.9.2
  test: ^1.15.7
