# This is a basic workflow to help you get started with Actions

name: Run Tests

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  test:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - name: Setup Dart Action
        # You may pin to the exact commit or the version.
        # uses: cedx/setup-dart@6ad18569ab4db516faa39d8a7efa6f4b8d1198f7
        uses: cedx/setup-dart@v2.5.0
        with:
          # The processor architecture of the Dart SDK ("x64", "ia32", "arm64" or "arm64").
          architecture: x64
          # The release channel of the Dart SDK ("stable", "beta" or "dev").
          release-channel: stable
          # The version of the Dart SDK.
          version: latest
      
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      # Runs a single command using the runners shell
      - name: Run test script
        run: ./testserver/actions.sh
